name: Update Versions in Chart.yml

on:
  workflow_dispatch:
    inputs:
      image-version: 
        description: "Version to set app-version to"
        required: true
      path-to-chart-yaml:
        description: "Path to Chart.yaml file that should be updated"
        required: true

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python script
        run: python update_chart_versions.py --appVersion ${{ inputs.image-version }} --pathToChartYaml ${{ inputs.path-to-chart-yaml }}
      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated Chart.yaml" --allow-empty)
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
      
