name: Update Versions in Chart.yml

on:
  workflow_dispatch:
    inputs:
      image-version: 
        description: "Version to set app-version to"
        required: false
        default: 1.2.0
      path-to-chart-yaml:
        description: "Path to Chart.yaml file that should be updated"
        required: false
        default: charts/backend/Chart.yaml
  repository_dispatch:
    types: [trigger-event]
    inputs:
      image-version: 
        description: "Version to set app-version to"
        required: false
        default: 1.2.0
      path-to-chart-yaml:
        description: "Path to Chart.yaml file that should be updated"
        required: false
        default: charts/backend/Chart.yaml
permissions:
  contents: write

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python script
        run: python update_chart_versions.py --appVersion ${{ inputs.image-version }} --pathToChartYaml ${{ inputs.path-to-chart-yaml }}
      - name: Commit Files
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Updated Chart.yaml"
          git push
      
