name: Update Versions in Chart.yml

on:
  workflow_dispatch:
    inputs:
      app-version: 
        description: "New App-Version"
        required: true
      path-to-chart-yaml:
        description: "Path to Chart.yaml"
        required: true
  repository_dispatch:
    types: [trigger-event]
permissions:
  contents: write
  pull-requests: write

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python script with input from workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: python update_chart_versions.py --appVersion ${{ inputs.app-version }} --pathToChart ${{ inputs.path-to-chart-yaml }}
      - name: Run Python script with input from repository_dispatch
        if: github.event_name == 'repository_dispatch'
        run: python update_chart_versions.py --appVersion ${{ github.event.client_payload.app-version }} --pathToChart ${{ github.event.client_payload.path-to-chart-yaml }}
      - name: Commit Files and create Pull-Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          if [ -n "$(git status --porcelain)" ]; then
            NEW_BRANCH="update-versions-$(date +%Y%m%d%H%M%S)"
            git checkout -b $NEW_BRANCH
            git commit -am "Updated Versions"
            git push --set-upstream origin $NEW_BRANCH
            gh pr create --base main --head $NEW_BRANCH --title "Update Versions for Chart" --body "This PR updates the versions in Chart.yaml files."
          else
            echo "No changes to commit"
          fi
      
