name: Update Image-Tag in values.yaml

on:
  workflow_dispatch:
    inputs:
      path-to-values-yaml: 
        description: "Path to values.yaml"
        required: true
      image-tag:
        description: "New Image-Tag"
        required: true
      path-to-image-tag-field-in-file:
        description: "Path/Keys to Image-Tag Field in values.yaml file"
        required: true
      path-to-chart-yaml:
        description: "Path to Chart.yaml"
        required: true
permissions:
  contents: write
  pull-requests: write
env:
  GH_TOKEN: ${{ github.token }}
  REPO_URL: "https://github.com/${{ github.repository }}"
  PATH_TO_VALUES_FILE: ${{ inputs.path-to-values-yaml }}
  IMAGE_TAG: ${{ inputs.image-tag }}
  PATH_TO_IMAGE_TAG: ${{ inputs.path-to-image-tag-field-in-file }}
  PATH_TO_CHART: ${{ inputs.path-to-chart-yaml }}

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python script
        run: python update_image_version_in_values_yaml.py --pathToValuesYaml $PATH_TO_VALUES_FILE --imageTag $IMAGE_TAG --pathToImageTagField $PATH_TO_IMAGE_TAG --pathToChart $PATH_TO_CHART
      - name: Commit Files and create Pull-Request
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          if [ -n "$(git status --porcelain)" ]; then
            NEW_BRANCH="update-$PATH_TO_VALUES_FILE-$IMAGE_TAG"
            PR_TITLE="Update Image-Tag in $PATH_TO_VALUES_FILE to $IMAGE_TAG"
            PR_BODY="This PR updates the Image-Tag in [$PATH_TO_VALUES_FILE]($REPO_URL/blob/$NEW_BRANCH/$PATH_TO_VALUES_FILE) to `$IMAGE_TAG`"
            git fetch --all
            git commit -am "Update Image-Tag in $PATH_TO_VALUES_FILE to $IMAGE_TAG"
            if git show-ref --verify --quiet refs/remotes/origin/$NEW_BRANCH; then
              git checkout $NEW_BRANCH
              git pull
            else
              git checkout -b $NEW_BRANCH
            fi
            git push --set-upstream origin $NEW_BRANCH
            gh pr create --base main --head $NEW_BRANCH --title "$PR_TITLE" --body "$PR_BODY"
          else
            echo "No changes to commit"
          fi
