name: Update Versions in Chart.yml

on:
  workflow_dispatch:
    inputs:
      image-version: 
        description: "Version to set app-version to"
        required: true
      path-to-chart-yaml:
        description: "Path to Chart.yaml"
        required: true
        default: Chart.yaml
      path-to-backend-chart:
        description: "Path to backend Chart.yaml"
        required: true
        default: charts/backend/Chart.yaml
      path-to-frontend-chart:
        description: "Path to frontend Chart.yaml"
        required: true
        default: charts/frontend/Chart.yaml
  repository_dispatch:
    types: [trigger-event]
permissions:
  contents: write

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python script with input from workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: python update_chart_versions.py --appVersion ${{ inputs.image-version }} --pathToChart ${{ inputs.path-to-chart-yaml }} --pathToBackendChart ${{ inputs.path-to-backend-chart }} --pathToFrontendChart ${{ inputs.path-to-frontend-chart }}
      - name: Run Python script with input from repository_dispatch
        if: github.event_name == 'repository_dispatch'
        run: python update_chart_versions.py --appVersion ${{ github.event.client_payload.image-version }} --pathToChart ${{ github.event.client_payload.path-to-chart-yaml }} --pathToBackendChart ${{ github.event.client_payload.path-to-backend-chart }} --pathToFrontendChart ${{ github.event.client_payload.path-to-frontend-chart }}
      - name: Commit Files
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Updated Chart.yaml"
          git push
      
